resource "local_file" "newText" {
  content  = var.content
  filename = var.filename
  file_permission = var.file_permission
}

resource "local_file" "app" {
  content  = "My app is called ${random_pet.pet.id}"
  filename = var.filename2

  depends_on = [ random_pet.pet ]

}


resource "random_pet" "pet" {
  prefix = var.prefix-name[0]
  separator = "."
  length = "1"
}

# output
# output "<variable_name>" {
#  value = <variable_name>
# <arguments>
# }

output pet-name {
  value = random_pet.pet.id
  description = "Record the value of Pet ID generated by the random_pet resource"
}

